using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;

namespace Skylotus.Tests.PlayMode
{
    /// <summary>
    /// PlayMode coverage for the two WP-1 criteria that no batchmode <c>-executeMethod</c> could
    /// reach: that booting registers every core system in the documented order with no
    /// double-registration warning, and that changing a serialized value on the core systems
    /// prefab observably changes runtime behaviour — the actual point of the package.
    ///
    /// <b>Isolation.</b> WP-5's editor auto-bootstrap has already run a full boot by the time any
    /// play-mode test starts, and a boot cannot be observed after the fact. The registration case
    /// therefore snapshots the live <see cref="ServiceLocator"/> contents, resets the locator and
    /// the bootstrapper's one-shot guard, drives a second real boot, asserts on it, then destroys
    /// the systems it created and restores the original registrations — so every other fixture
    /// still resolves the systems the auto-bootstrap brought up. Unity's own project settings are
    /// captured and restored too, because the boot applies saved settings.
    /// </summary>
    [TestFixture]
    public class BootstrapTests
    {
        /// <summary>Canonical path of the core systems prefab generated by <c>SkylotusCI</c>.</summary>
        private const string CoreSystemsPrefabPath = "Assets/Resources/Prefabs/SkylotusCoreSystems.prefab";

        /// <summary>
        /// The registration sequence <see cref="Bootstrapper"/> documents, as
        /// <see cref="ServiceLocator"/> types. <c>GameLogger</c> is static and
        /// <c>DebugConsole</c> owns its own singleton, so neither is registered.
        /// <c>ColorPalette</c> is registered only when one is assigned, so it is optional here.
        /// </summary>
        private static readonly Type[] _documentedOrder =
        {
            typeof(SaveSystem),
            typeof(LocalizationSystem),
            typeof(SettingsService),
            typeof(AudioManager),
            typeof(ObjectPool),
            typeof(SceneManager),
            typeof(GameStateMachine),
            typeof(TimeManager),
            typeof(InputManager),
            typeof(Skylotus.Core.UI.ColorPalette),
            typeof(UIManager),
            typeof(DialogueSystem),
            typeof(NotificationSystem)
        };

        /// <summary>Systems that must be registered by every boot, prefab path or not.</summary>
        private static readonly Type[] _mandatorySystems =
        {
            typeof(SaveSystem),
            typeof(LocalizationSystem),
            typeof(SettingsService),
            typeof(AudioManager),
            typeof(ObjectPool),
            typeof(SceneManager),
            typeof(GameStateMachine),
            typeof(TimeManager),
            typeof(UIManager),
            typeof(DialogueSystem),
            typeof(NotificationSystem)
        };

        /// <summary>The quality level that was active before this fixture ran.</summary>
        private int _originalQualityLevel;

        /// <summary>Each quality level's <c>vSyncCount</c> before this fixture ran.</summary>
        private int[] _originalVSync;

        /// <summary>Capture the project settings a boot is allowed to touch.</summary>
        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            _originalQualityLevel = QualitySettings.GetQualityLevel();
            _originalVSync = CaptureVSyncPerLevel();
        }

        /// <summary>Write the project settings back.</summary>
        [OneTimeTearDown]
        public void OneTimeTearDown()
        {
            RestoreVSyncPerLevel(_originalVSync);
            QualitySettings.SetQualityLevel(_originalQualityLevel, true);
        }

        // ─── WP-1: a serialized value drives runtime behaviour ──────

        /// <summary>
        /// WP-1's actual point: a value authored on the core systems prefab reaches the running
        /// component. Before WP-1 the systems were built with <c>AddComponent</c>, so every
        /// <c>[SerializeField]</c> was stuck at its compile-time default, permanently and
        /// unreachably.
        ///
        /// Two distinct pool sizes are set on two fresh instances of the prefab's own
        /// <c>AudioManager</c> — neither equal to the field's compile-time default of 16 — and the
        /// number of SFX <c>AudioSource</c> children each one creates in <c>Awake</c> is counted.
        /// The instance is kept dormant under an inactive parent while the value is written, the
        /// same trick <c>Bootstrapper.RegisterSystemsFromPrefab</c> uses, so <c>Awake</c> observes
        /// the authored value rather than the default.
        /// </summary>
        [Test]
        public void CoreSystemsPrefab_SerializedSfxPoolSize_DrivesTheRuntimeSourceCount()
        {
            var prefab = LoadCoreSystemsPrefab();
            Assert.IsNotNull(prefab, $"No core systems prefab at {CoreSystemsPrefabPath}.");

            int authored = AuthoredSfxPoolSize(prefab);
            Assert.AreEqual(authored, SpawnAudioManagerWithPoolSize(prefab, authored),
                "The prefab's own authored value should be the one Awake honours.");

            Assert.AreEqual(4, SpawnAudioManagerWithPoolSize(prefab, 4),
                "An _sfxPoolSize of 4 should produce four SFX sources.");
            Assert.AreEqual(9, SpawnAudioManagerWithPoolSize(prefab, 9),
                "An _sfxPoolSize of 9 should produce nine SFX sources.");
        }

        /// <summary>
        /// The running <see cref="AudioManager"/> is the prefab's, not a code-constructed one: its
        /// mixer reference is assigned, which only a serialized value can do.
        /// </summary>
        [Test]
        public void RegisteredAudioManager_CameFromThePrefabWithItsMixerAssigned()
        {
            Assert.IsTrue(ServiceLocator.TryGet<AudioManager>(out var audio),
                "No AudioManager is registered — the core systems are not up.");

            Assert.IsNotNull(audio.Mixer,
                "AudioManager.Mixer is null at runtime, which means the boot fell back to " +
                "code-constructed systems and no inspector value reached anything.");
        }

        // ─── WP-1: registration set, order, and no double-registration ─

        /// <summary>
        /// WP-1's remaining carried-over criterion: a boot registers every core system, in the
        /// documented order, with no "Overwriting service" warning from
        /// <c>ServiceLocator.Register</c>.
        ///
        /// <b>How order is observed.</b> <see cref="ServiceLocator"/> exposes no registration hook,
        /// so the order is read back from its private <c>Dictionary&lt;Type, object&gt;</c>. A
        /// dictionary that has had no removals enumerates in insertion order on this runtime; the
        /// locator is reset immediately before the boot and nothing unregisters during it, so that
        /// holds here. It is an implementation detail rather than a documented guarantee — if this
        /// test ever starts reporting a scrambled order, check that before assuming the boot broke.
        /// </summary>
        [UnityTest]
        public IEnumerator Boot_RegistersEverySystemInOrderWithNoDoubleRegistration()
        {
            var prefab = LoadCoreSystemsPrefab();
            Assert.IsNotNull(prefab, $"No core systems prefab at {CoreSystemsPrefabPath}.");

            var savedServices = SnapshotServices();
            var existingAudio = new HashSet<int>();
            foreach (var manager in UnityEngine.Object.FindObjectsByType<AudioManager>(
                         FindObjectsInactive.Include, FindObjectsSortMode.None))
                existingAudio.Add(manager.GetInstanceID());

            var warnings = new List<string>();
            var errors = new List<string>();

            void Capture(string condition, string stackTrace, LogType type)
            {
                if (type == LogType.Warning) warnings.Add(condition);
                else if (type == LogType.Error || type == LogType.Exception) errors.Add(condition);
            }

            GameObject host = null;
            GameObject newCoreRoot = null;

            Application.logMessageReceived += Capture;

            try
            {
                // A boot cannot be watched after the fact, so run a real one from a clean locator.
                ServiceLocator.Reset();
                SetBootstrapperInitialized(false);

                host = new GameObject("BootstrapTests_Bootstrapper");
                host.SetActive(false);

                var bootstrapper = host.AddComponent<Bootstrapper>();

                // Stay put: this test is about registration, not scene flow.
                SetPrivateField(bootstrapper, "_firstScene", string.Empty);
                SetPrivateField(bootstrapper, "_coreSystemsPrefab", prefab);

                // The console is not a ServiceLocator registration and it owns a static singleton
                // slot the auto-bootstrap's console already holds; leaving it out keeps this boot
                // from fighting that one over a system the criterion does not cover.
                SetPrivateField(bootstrapper, "_enableDebugConsole", false);

                // Activating runs Bootstrapper.Awake, which is the whole boot.
                host.SetActive(true);

                // Start() runs a frame later; with an empty _firstScene it does nothing, but let it
                // happen inside the measured window rather than during another test.
                yield return null;

                newCoreRoot = FindNewCoreRoot(existingAudio);

                // ── Every system is registered ──────────────────────
                foreach (var type in _mandatorySystems)
                {
                    Assert.IsTrue(IsRegistered(type),
                        $"{type.Name} was not registered by the boot.");
                }

                // ── In the documented order ─────────────────────────
                var observed = RegisteredTypesInInsertionOrder();
                var expected = new List<Type>();
                foreach (var type in _documentedOrder)
                    if (observed.Contains(type)) expected.Add(type);

                CollectionAssert.AreEqual(expected, observed,
                    "Registration order does not match the sequence Bootstrapper documents.\n" +
                    $"expected: {string.Join(" -> ", expected.ConvertAll(t => t.Name))}\n" +
                    $"observed: {string.Join(" -> ", observed.ConvertAll(t => t.Name))}");

                // ── With no double registration ─────────────────────
                var overwrites = warnings.FindAll(w => w.Contains("Overwriting service"));
                Assert.IsEmpty(overwrites,
                    "ServiceLocator reported a double registration during boot:\n" +
                    string.Join("\n", overwrites));

                Assert.IsEmpty(errors, "The boot logged errors:\n" + string.Join("\n", errors));
            }
            finally
            {
                Application.logMessageReceived -= Capture;

                if (newCoreRoot != null) UnityEngine.Object.DestroyImmediate(newCoreRoot);
                if (host != null) UnityEngine.Object.DestroyImmediate(host);

                RestoreServices(savedServices);
                SetBootstrapperInitialized(true);
            }
        }

        // ─── Helpers: the prefab ────────────────────────────────────

        /// <summary>
        /// Load the core systems prefab asset. Uses <c>AssetDatabase</c> rather than
        /// <c>Resources.Load</c>: the codebase forbids new <c>Resources</c> call sites, and a test
        /// assembly only ever runs inside the Editor.
        /// </summary>
        /// <returns>The prefab, or null when it is missing.</returns>
        private static GameObject LoadCoreSystemsPrefab()
        {
#if UNITY_EDITOR
            return UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(CoreSystemsPrefabPath);
#else
            Assert.Ignore("The core systems prefab can only be loaded as an asset in the Editor.");
            return null;
#endif
        }

        /// <summary>Read the <c>_sfxPoolSize</c> value authored on the prefab.</summary>
        /// <param name="prefab">The core systems prefab.</param>
        /// <returns>The authored pool size.</returns>
        private static int AuthoredSfxPoolSize(GameObject prefab)
        {
            var audio = prefab.GetComponentInChildren<AudioManager>(true);
            Assert.IsNotNull(audio, "The core systems prefab carries no AudioManager.");

            return (int)FieldOf(audio, "_sfxPoolSize").GetValue(audio);
        }

        /// <summary>
        /// Instantiate the prefab's <see cref="AudioManager"/> with a given <c>_sfxPoolSize</c> and
        /// count the SFX sources its <c>Awake</c> creates.
        ///
        /// The instance is built under an inactive parent so no <c>Awake</c> runs until the value
        /// is written, then the AudioManager alone is detached and activated — the rest of the
        /// prefab is destroyed while still dormant, so no other system wakes up.
        /// </summary>
        /// <param name="prefab">The core systems prefab.</param>
        /// <param name="poolSize">The value to write before activation.</param>
        /// <returns>The number of SFX AudioSource children created.</returns>
        private static int SpawnAudioManagerWithPoolSize(GameObject prefab, int poolSize)
        {
            var staging = new GameObject("BootstrapTests_Staging");
            staging.SetActive(false);

            GameObject audioObject = null;

            try
            {
                var instance = UnityEngine.Object.Instantiate(prefab, staging.transform);
                var audio = instance.GetComponentInChildren<AudioManager>(true);
                Assert.IsNotNull(audio, "The instantiated prefab carries no AudioManager.");

                FieldOf(audio, "_sfxPoolSize").SetValue(audio, poolSize);

                audioObject = audio.gameObject;
                audioObject.transform.SetParent(null, worldPositionStays: false);

                // Everything else goes away before it can wake.
                UnityEngine.Object.DestroyImmediate(staging);
                staging = null;

                audioObject.SetActive(true);

                int sources = 0;
                foreach (Transform child in audioObject.transform)
                    if (child.name.StartsWith("SFX_", StringComparison.Ordinal)) sources++;

                return sources;
            }
            finally
            {
                if (audioObject != null) UnityEngine.Object.DestroyImmediate(audioObject);
                if (staging != null) UnityEngine.Object.DestroyImmediate(staging);
            }
        }

        /// <summary>Find the core systems root created by the boot this test just drove.</summary>
        /// <param name="preExisting">Instance IDs of the AudioManagers that existed beforehand.</param>
        /// <returns>The new root GameObject, or null if none was created.</returns>
        private static GameObject FindNewCoreRoot(HashSet<int> preExisting)
        {
            foreach (var manager in UnityEngine.Object.FindObjectsByType<AudioManager>(
                         FindObjectsInactive.Include, FindObjectsSortMode.None))
            {
                if (!preExisting.Contains(manager.GetInstanceID()))
                    return manager.transform.root.gameObject;
            }

            return null;
        }

        // ─── Helpers: ServiceLocator introspection ──────────────────

        /// <summary>The locator's private live-instance dictionary.</summary>
        /// <returns>The dictionary itself, not a copy.</returns>
        private static IDictionary ServicesDictionary()
        {
            var field = typeof(ServiceLocator).GetField(
                "_services", BindingFlags.Static | BindingFlags.NonPublic);

            Assert.IsNotNull(field, "ServiceLocator._services not found — was it renamed?");
            return (IDictionary)field.GetValue(null);
        }

        /// <summary>Whether a service of the given type is registered.</summary>
        /// <param name="type">The registered type to look for.</param>
        /// <returns>True when the locator holds an instance for it.</returns>
        private static bool IsRegistered(Type type) => ServicesDictionary().Contains(type);

        /// <summary>Read the registered types in the order they were added.</summary>
        /// <returns>The registered types, in dictionary enumeration order.</returns>
        private static List<Type> RegisteredTypesInInsertionOrder()
        {
            var types = new List<Type>();
            foreach (DictionaryEntry entry in ServicesDictionary())
                types.Add((Type)entry.Key);

            return types;
        }

        /// <summary>Copy the locator's current registrations so they can be put back.</summary>
        /// <returns>The registered types paired with their instances, in order.</returns>
        private static List<KeyValuePair<Type, object>> SnapshotServices()
        {
            var snapshot = new List<KeyValuePair<Type, object>>();
            foreach (DictionaryEntry entry in ServicesDictionary())
                snapshot.Add(new KeyValuePair<Type, object>((Type)entry.Key, entry.Value));

            return snapshot;
        }

        /// <summary>Replace the locator's contents with a previously taken snapshot.</summary>
        /// <param name="snapshot">The snapshot from <see cref="SnapshotServices"/>.</param>
        private static void RestoreServices(List<KeyValuePair<Type, object>> snapshot)
        {
            var services = ServicesDictionary();
            services.Clear();

            foreach (var pair in snapshot)
                services[pair.Key] = pair.Value;
        }

        /// <summary>Set <c>Bootstrapper</c>'s static one-shot guard.</summary>
        /// <param name="value">The value to write.</param>
        private static void SetBootstrapperInitialized(bool value)
        {
            var field = typeof(Bootstrapper).GetField(
                "_initialized", BindingFlags.Static | BindingFlags.NonPublic);

            Assert.IsNotNull(field, "Bootstrapper._initialized not found — was it renamed?");
            field.SetValue(null, value);
        }

        // ─── Helpers: reflection and project settings ───────────────

        /// <summary>Assign a <c>[SerializeField] private</c> field on a component created at runtime.</summary>
        /// <param name="target">Instance whose private field is being set.</param>
        /// <param name="fieldName">Name of the private instance field.</param>
        /// <param name="value">Value to assign.</param>
        private static void SetPrivateField(object target, string fieldName, object value)
        {
            FieldOf(target, fieldName).SetValue(target, value);
        }

        /// <summary>Locate a private instance field, failing the test with a clear message if it moved.</summary>
        /// <param name="target">The instance whose type is searched.</param>
        /// <param name="fieldName">Name of the private field.</param>
        /// <returns>The field.</returns>
        private static FieldInfo FieldOf(object target, string fieldName)
        {
            FieldInfo field = null;
            for (var type = target.GetType(); type != null && field == null; type = type.BaseType)
                field = type.GetField(fieldName, BindingFlags.Instance | BindingFlags.NonPublic);

            Assert.IsNotNull(field,
                $"{target.GetType().Name} has no field '{fieldName}' — was it renamed?");
            return field;
        }

        /// <summary>
        /// Read <c>vSyncCount</c> for every quality level. It belongs to the active level, not to
        /// the project, so restoring it after a level switch would otherwise write onto the wrong
        /// level and dirty <c>ProjectSettings/QualitySettings.asset</c>.
        /// </summary>
        /// <returns>One entry per quality level, in level order.</returns>
        private static int[] CaptureVSyncPerLevel()
        {
            int active = QualitySettings.GetQualityLevel();
            var captured = new int[QualitySettings.names.Length];

            for (int i = 0; i < captured.Length; i++)
            {
                QualitySettings.SetQualityLevel(i, false);
                captured[i] = QualitySettings.vSyncCount;
            }

            QualitySettings.SetQualityLevel(active, false);
            return captured;
        }

        /// <summary>Write back every quality level's <c>vSyncCount</c>.</summary>
        /// <param name="captured">The array returned by <see cref="CaptureVSyncPerLevel"/>.</param>
        private static void RestoreVSyncPerLevel(int[] captured)
        {
            int active = QualitySettings.GetQualityLevel();

            for (int i = 0; i < captured.Length && i < QualitySettings.names.Length; i++)
            {
                QualitySettings.SetQualityLevel(i, false);
                QualitySettings.vSyncCount = captured[i];
            }

            QualitySettings.SetQualityLevel(active, false);
        }
    }
}
