using System.Reflection;
using Skylotus.Core.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.InputSystem;

namespace Skylotus.Editor
{
    // WP-5 — pressing Play in any scene but BootScene throws.
    //
    // ServiceLocator.Get<T>() throws when a service is missing, so every screen that resolves a
    // system in Awake (MainMenuScreen, SettingsScreen, the settings tabs) dies on the first line
    // when the scene has no Bootstrapper. Gameplay.unity and MainMenu.unity have none, so every
    // iteration had to route through BootScene.
    //
    // This file lives under Assets/Scripts/Editor, so it compiles into Assembly-CSharp-Editor and
    // is never part of a player build. Nothing here has any effect on a built game.

    /// <summary>
    /// Editor-only auto-bootstrap: when play mode is entered from a scene that has no
    /// <see cref="Bootstrapper"/>, this spawns one before the scene's own <c>Awake</c> calls run,
    /// then leaves the developer in the scene they were editing.
    ///
    /// <b>Mechanism.</b> Two hooks, one action:
    /// <list type="number">
    /// <item><c>ExitingEditMode</c> — the open scenes are still loaded and are the only place the
    ///       question "does this scene already have a bootstrapper?" can be answered. The verdict
    ///       is parked in <see cref="SessionState"/>, which survives the domain reload that
    ///       entering play mode triggers.</item>
    /// <item><c>RuntimeInitializeOnLoadMethod(BeforeSceneLoad)</c> — fires after that reload and
    ///       before the first scene's objects are activated, which is the only window where the
    ///       systems can be up before <c>MainMenuScreen.Awake</c> asks for them.</item>
    /// </list>
    /// A third hook at <c>EnteredPlayMode</c> is a diagnostic safety net: if the runtime hook did
    /// not fire, it bootstraps late and says so loudly, rather than failing silently.
    ///
    /// <b>Reuses the real boot path.</b> It does not initialize anything itself. It creates a
    /// dormant GameObject, adds a real <see cref="Bootstrapper"/>, injects the two asset
    /// references the boot scene would have carried, and activates it — from there the ordinary
    /// <c>Bootstrapper.Awake</c> runs, including its prefab path and its code-construction
    /// fallback. Any change to the boot sequence is picked up here for free.
    ///
    /// <b>Why not <c>EditorSceneManager.playModeStartScene</c>.</b> Pointing that at
    /// <c>BootScene</c> is a two-line alternative, but it defeats the purpose: every Play press
    /// would start in BootScene and then load <c>_firstScene</c> (MainMenu), so a developer
    /// editing Gameplay.unity never sees their own scene. This approach keeps "press Play, stay in
    /// the scene I'm editing". The two are not made to fight: if a developer has deliberately set
    /// <c>playModeStartScene</c>, the auto-bootstrap stands down and lets that scene boot.
    /// </summary>
    public static class EditorBootstrap
    {
        // ─── Constants ──────────────────────────────────────────────

        /// <summary>Log category for this file's console output.</summary>
        private const string Category = "EditorBootstrap";

        /// <summary>
        /// SessionState key holding whether the scene play mode was entered from needs a
        /// bootstrapper. SessionState is used rather than a static field because entering play
        /// mode reloads the domain and wipes statics.
        /// </summary>
        private const string NeededKey = "Skylotus.EditorBootstrap.Needed";

        /// <summary>
        /// SessionState key marking that a bootstrapper has already been spawned for this play
        /// session, so the <c>EnteredPlayMode</c> safety net does not create a second one.
        /// </summary>
        private const string SpawnedKey = "Skylotus.EditorBootstrap.Spawned";

        /// <summary>Canonical path of the core systems prefab generated by <c>SkylotusCI</c>.</summary>
        private const string CoreSystemsPrefabPath = "Assets/Resources/Prefabs/SkylotusCoreSystems.prefab";

        /// <summary>Canonical path of the project's color palette asset.</summary>
        private const string ColorPalettePath = "Assets/Resources/ScriptableObjects/ColorPalette.asset";

        /// <summary>Canonical path of the project's Input Action Asset.</summary>
        private const string InputActionsPath = "Assets/InputSystem_Actions.inputactions";

        // ─── Installation ───────────────────────────────────────────

        /// <summary>
        /// Subscribe to play mode transitions. Runs on every domain reload; the unsubscribe first
        /// is defensive against a reload that preserved the delegate list.
        /// </summary>
        [InitializeOnLoadMethod]
        private static void Install()
        {
            EditorApplication.playModeStateChanged -= OnPlayModeStateChanged;
            EditorApplication.playModeStateChanged += OnPlayModeStateChanged;
        }

        /// <summary>
        /// Decide (on the way out of edit mode) whether this play session needs a bootstrapper,
        /// and catch (on the way in) the case where the runtime hook never fired.
        /// </summary>
        /// <param name="change">The play mode transition being reported.</param>
        private static void OnPlayModeStateChanged(PlayModeStateChange change)
        {
            switch (change)
            {
                case PlayModeStateChange.ExitingEditMode:
                    SessionState.SetBool(NeededKey, ShouldAutoBootstrap());
                    SessionState.SetBool(SpawnedKey, false);
                    break;

                case PlayModeStateChange.EnteredPlayMode:
                    if (SessionState.GetBool(NeededKey, false) && !SessionState.GetBool(SpawnedKey, false))
                    {
                        // BeforeSceneLoad did not run. The scene's Awake calls have already
                        // happened and anything that resolved a service in Awake has already
                        // thrown, so this is damage control, not a working configuration.
                        Debug.LogWarning($"[{Category}] The before-scene-load hook did not fire; " +
                                         "core systems are being created after the scene's Awake " +
                                         "calls. Expect service-resolution exceptions from this " +
                                         "session. Re-enter play mode to get a clean boot.");
                        SpawnBootstrapper();
                    }
                    break;

                case PlayModeStateChange.EnteredEditMode:
                    SessionState.SetBool(NeededKey, false);
                    SessionState.SetBool(SpawnedKey, false);
                    break;
            }
        }

        // ─── Hooks ──────────────────────────────────────────────────

        /// <summary>
        /// Spawn the bootstrapper before the first scene's objects are activated. Unity runs
        /// <c>BeforeSceneLoad</c> callbacks after the domain reload and before any scene
        /// <c>Awake</c>, which is the whole point of doing it here rather than at
        /// <c>EnteredPlayMode</c>.
        /// </summary>
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        private static void BeforeSceneLoad()
        {
            if (!SessionState.GetBool(NeededKey, false))
                return;

            if (SessionState.GetBool(SpawnedKey, false))
                return;

            SpawnBootstrapper();
        }

        // ─── Decision ───────────────────────────────────────────────

        /// <summary>
        /// Whether the scenes currently open in the editor need an auto-bootstrap.
        /// </summary>
        /// <returns>
        /// False when a <see cref="Bootstrapper"/> is already present (BootScene, or a scene the
        /// developer has added one to), or when a play mode start scene is configured — in that
        /// case the developer has chosen an explicit boot path and this must not compete with it.
        /// True otherwise.
        /// </returns>
        private static bool ShouldAutoBootstrap()
        {
            if (EditorSceneManager.playModeStartScene != null)
                return false;

            // Inactive objects count: a disabled bootstrapper is a deliberate choice, and adding a
            // second one would give the scene two competing boot paths.
            var existing = UnityEngine.Object.FindFirstObjectByType<Bootstrapper>(
                FindObjectsInactive.Include);

            return existing == null;
        }

        // ─── Spawning ───────────────────────────────────────────────

        /// <summary>
        /// Create a <see cref="Bootstrapper"/> configured the way the boot scene's one is, minus
        /// the scene hand-off, and let its own <c>Awake</c> bring the systems up.
        ///
        /// The GameObject is created inactive so that <c>AddComponent</c> does not fire
        /// <c>Awake</c> before the asset references are in place — Unity defers <c>Awake</c> for
        /// components on inactive objects, and activating the object runs it. This is the same
        /// dormant-staging trick <c>Bootstrapper.RegisterSystemsFromPrefab</c> uses.
        ///
        /// Only the two references that decide behaviour are injected. Everything else keeps the
        /// <see cref="Bootstrapper"/>'s compile-time defaults, which match the boot scene's
        /// authored values (console on, file logging off, language "en", no save encryption key).
        /// </summary>
        private static void SpawnBootstrapper()
        {
            // Set first: SpawnBootstrapper must never run twice for one play session, even if the
            // work below throws part-way through.
            SessionState.SetBool(SpawnedKey, true);

            var host = new GameObject("[Skylotus Editor Bootstrap]");
            host.SetActive(false);

            var bootstrapper = host.AddComponent<Bootstrapper>();

            // Stay in the scene being edited. This is the entire reason this exists rather than
            // playModeStartScene: the boot scene's bootstrapper would load MainMenu from Start.
            SetPrivateField(bootstrapper, "_firstScene", string.Empty);

            var prefab = LoadAsset<GameObject>(CoreSystemsPrefabPath, "SkylotusCoreSystems t:Prefab");
            if (prefab == null)
            {
                Debug.LogWarning($"[{Category}] No core systems prefab at {CoreSystemsPrefabPath}. " +
                                 "Falling back to code-constructed systems with default inspector " +
                                 "values. Run SkylotusCI.GenerateCoreSystemsPrefab.");
            }
            else
            {
                SetPrivateField(bootstrapper, "_coreSystemsPrefab", prefab);
            }

            // Registered by both boot paths, and read through ServiceLocator.TryGet, so a missing
            // palette degrades to default colors rather than throwing.
            var palette = LoadAsset<ColorPalette>(ColorPalettePath, "t:ColorPalette");
            if (palette != null)
                SetPrivateField(bootstrapper, "_colorPalette", palette);

            // Only consumed by the code-construction fallback; harmless when the prefab is present,
            // and the difference between input working and not when it is missing.
            var inputActions = LoadAsset<InputActionAsset>(InputActionsPath, "t:InputActionAsset");
            if (inputActions != null)
                SetPrivateField(bootstrapper, "_inputActions", inputActions);

            // Activating runs Bootstrapper.Awake, which claims the _initialized guard, marks itself
            // DontDestroyOnLoad and initializes every system.
            host.SetActive(true);

            Debug.Log($"[{Category}] No Bootstrapper in the open scene — core systems were " +
                      "auto-bootstrapped for this play session. This is editor-only; a built " +
                      "player still requires a Bootstrapper in its first scene.");
        }

        // ─── Helpers ────────────────────────────────────────────────

        /// <summary>
        /// Assign a <c>[SerializeField] private</c> field on a component created at runtime.
        /// Reflection is unavoidable: the component was added with <c>AddComponent</c>, so there
        /// is no serialized data to carry the reference and <see cref="Bootstrapper"/> exposes no
        /// setters. <c>Bootstrapper.RegisterSystemsFromCode</c> injects <c>InputManager</c>'s
        /// action asset the same way.
        /// </summary>
        /// <param name="target">Instance whose private field is being set.</param>
        /// <param name="fieldName">Name of the private instance field.</param>
        /// <param name="value">Value to assign.</param>
        private static void SetPrivateField(object target, string fieldName, object value)
        {
            var field = target.GetType().GetField(
                fieldName, BindingFlags.NonPublic | BindingFlags.Instance);

            if (field == null)
            {
                Debug.LogError($"[{Category}] {target.GetType().Name} has no field '{fieldName}'. " +
                               "The auto-bootstrap needs updating to match it.");
                return;
            }

            field.SetValue(target, value);
        }

        /// <summary>
        /// Load an asset by its canonical path, falling back to a project-wide search so a moved
        /// or renamed asset degrades to a slower lookup instead of a broken play session.
        /// <c>AssetDatabase</c> rather than <c>Resources.Load</c>: this is editor-only code, and
        /// the runtime is deliberately kept free of new <c>Resources</c> lookups.
        /// </summary>
        /// <typeparam name="T">Asset type to load.</typeparam>
        /// <param name="path">Canonical project-relative path, tried first.</param>
        /// <param name="searchFilter">
        /// <c>AssetDatabase.FindAssets</c> filter used when the path misses.
        /// </param>
        /// <returns>The asset, or null when neither the path nor the search finds one.</returns>
        private static T LoadAsset<T>(string path, string searchFilter) where T : UnityEngine.Object
        {
            var asset = AssetDatabase.LoadAssetAtPath<T>(path);
            if (asset != null)
                return asset;

            foreach (var guid in AssetDatabase.FindAssets(searchFilter))
            {
                var found = AssetDatabase.LoadAssetAtPath<T>(AssetDatabase.GUIDToAssetPath(guid));
                if (found != null)
                    return found;
            }

            return null;
        }
    }
}
